### ISSUE TITLE
relativity

### ISSUE THREAD

**Issue by anandOAB** [degeta10/GPS_Based_AR#1]
hi Devender ,
how can we set location of the object relative to coordinate and mobile coordinates.means in which direction the object is set virtualy.
BTW its a great code.. thanks

**Comment by devender-gupta** [comment]
Hey,
Actually even did think of it. But i dont think if its possible. You can actually get the direction if your object is placed in a position like: 

" go.GetComponent<Rigidbody>().velocity = (GameObject.Find (targetname).transform.position -  GameObject.Find(currentobject).transform.position).normalized * Power; "

But this code is used to shoot a projectile towards another object.
I have no clue on placing an object in a specific location.
Because the distance of the gameobject from the Main Camera is something that is already set.
So the direction in which you point your device when the app just starts to works is taken and according to that everything is placed in the world.
I hope you understood!
Snapchat's AR is a very interesting feature. I'm amazed how it works.
If you get any info please do share :)
Thanks

**Comment by anandOAB** [comment]
hi,
Actually vuforia also dosent support SLAM , if anyhow we can code that in this script that will also work for me,
i have manage the distance between camera and model by using "distance" value of coordinates.But i want to show the model on relative direction or at least SLAM effect in current one.
Thanks :)

**Comment by devender-gupta** [comment]
Yeah! SLAM is something thats not there in Vuforia.
See actually if there are two objects: A & B. if we know the "transform.position" of these two objects, then we can get the direction for like: shooting projectiles between the objects.
So, I don't think there is anyway to implement it in this case.
Thanks

**Comment by anandOAB** [comment]
yeah,i think we get direct positive value "distance" from distance calculation code.
so we cant use transform position to show relativity using positive and negative values
thanks
